package membership

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/Pravasta/jualin-crm/crm_be/internal/shared/db"
	"github.com/Pravasta/jualin-crm/crm_be/internal/shared/httpx"
	"github.com/Pravasta/jualin-crm/crm_be/internal/shared/tenant"
)

// postgresRepository is the reference implementation every later
// tenant-scoped repository in this codebase copies. Every method takes
// tenant.Context as its first parameter and injects organization_id
// inside the query — it is never accepted as a separate argument a
// caller could get wrong, and there is no method here that omits it
// (docs/architecture/multi-tenancy.md lapis 1).
//
// Unexported since #11 — callers depend on the Repository interface
// (port.go), not this concrete type, so Usecase can be tested with a
// fake (ADR-011). Cross-package consumers (auth.Repos.Member) already
// only ever held the interface value New returns, so this rename is
// invisible to them.
type postgresRepository struct {
	q db.Querier
}

// New builds a Repository bound to q. Pass a *pgxpool.Pool for read-only
// use, or a pgx.Tx (inside db.InTx) when the write must be atomic with
// other tables — e.g. creating a membership alongside its organization
// during registration.
func New(q db.Querier) Repository {
	return &postgresRepository{q: q}
}

// FindByID returns the membership with id within t's organization.
// A membership belonging to another organization is indistinguishable
// from one that doesn't exist — it maps to httpx.ErrNotFound (404), never
// a 403 (Rule #6): a 403 would confirm the id exists, which is itself an
// information leak.
func (r *postgresRepository) FindByID(ctx context.Context, t tenant.Context, id uuid.UUID) (*Membership, error) {
	const q = `
		SELECT id, organization_id, user_id, role, created_at, updated_at, deleted_at
		FROM memberships
		WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`

	m, err := scanOne(r.q.QueryRow(ctx, q, id, t.OrganizationID))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, httpx.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("membership: find by id: %w", err)
	}
	return m, nil
}

// FindActiveByUserID returns every non-deleted membership a user holds,
// across every organization they belong to — this is the query
// ADR-007's multi-membership model exists to support, used at login to
// decide whether organization selection is required.
//
// This is the one method on this repository that is NOT organization-
// scoped by design: a user resolving "which of my organizations can I
// log into" must see across all of them. It still takes tenant.Context
// so the signature matches every other repository method, but
// t.OrganizationID is intentionally unused here.
func (r *postgresRepository) FindActiveByUserID(ctx context.Context, userID uuid.UUID) ([]*Membership, error) {
	const q = `
		SELECT id, organization_id, user_id, role, created_at, updated_at, deleted_at
		FROM memberships
		WHERE user_id = $1 AND deleted_at IS NULL
		ORDER BY created_at`

	rows, err := r.q.Query(ctx, q, userID)
	if err != nil {
		return nil, fmt.Errorf("membership: find active by user id: %w", err)
	}
	defer rows.Close()

	var out []*Membership
	for rows.Next() {
		m, err := scanRow(rows)
		if err != nil {
			return nil, fmt.Errorf("membership: scan: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("membership: find active by user id: %w", err)
	}
	return out, nil
}

// Create inserts a new membership. The caller supplies id (UUIDv7,
// generated by the application per Rule #12 — never a database DEFAULT).
func (r *postgresRepository) Create(ctx context.Context, t tenant.Context, id, userID uuid.UUID, role tenant.Role) (*Membership, error) {
	const q = `
		INSERT INTO memberships (id, organization_id, user_id, role)
		VALUES ($1, $2, $3, $4)
		RETURNING id, organization_id, user_id, role, created_at, updated_at, deleted_at`

	m, err := scanOne(r.q.QueryRow(ctx, q, id, t.OrganizationID, userID, role))
	if err != nil {
		return nil, fmt.Errorf("membership: create: %w", err)
	}
	return m, nil
}

// FindAllByOrgWithUser lists every active member of t's organization,
// joined with users for the display fields GET /v1/memberships needs —
// one query instead of an N+1 loop of FindByID-style lookups per member.
func (r *postgresRepository) FindAllByOrgWithUser(ctx context.Context, t tenant.Context) ([]*MemberWithUser, error) {
	const q = `
		SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at, m.updated_at, m.deleted_at,
		       u.email, u.full_name
		FROM memberships m
		JOIN users u ON u.id = m.user_id
		WHERE m.organization_id = $1 AND m.deleted_at IS NULL
		ORDER BY m.created_at`

	rows, err := r.q.Query(ctx, q, t.OrganizationID)
	if err != nil {
		return nil, fmt.Errorf("membership: find all by org with user: %w", err)
	}
	defer rows.Close()

	var out []*MemberWithUser
	for rows.Next() {
		var mu MemberWithUser
		if err := rows.Scan(
			&mu.ID, &mu.OrganizationID, &mu.UserID, &mu.Role, &mu.CreatedAt, &mu.UpdatedAt, &mu.DeletedAt,
			&mu.Email, &mu.FullName,
		); err != nil {
			return nil, fmt.Errorf("membership: scan with user: %w", err)
		}
		out = append(out, &mu)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("membership: find all by org with user: %w", err)
	}
	return out, nil
}

// UpdateRole changes id's role within t's organization. Rows-affected
// isn't checked here — Usecase already resolved id via FindByID (404 if
// cross-tenant or missing) immediately before calling this, so a zero
// match here would only happen from a race, not a routing bug.
func (r *postgresRepository) UpdateRole(ctx context.Context, t tenant.Context, id uuid.UUID, role tenant.Role) error {
	const q = `UPDATE memberships SET role = $1 WHERE id = $2 AND organization_id = $3 AND deleted_at IS NULL`
	_, err := r.q.Exec(ctx, q, role, id, t.OrganizationID)
	if err != nil {
		return fmt.Errorf("membership: update role: %w", err)
	}
	return nil
}

// Deactivate soft-deletes id within t's organization (Rule #18 — soft
// delete for business entities).
func (r *postgresRepository) Deactivate(ctx context.Context, t tenant.Context, id uuid.UUID) error {
	const q = `UPDATE memberships SET deleted_at = now() WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`
	_, err := r.q.Exec(ctx, q, id, t.OrganizationID)
	if err != nil {
		return fmt.Errorf("membership: deactivate: %w", err)
	}
	return nil
}

// CountActiveOwners is how Usecase.Deactivate and UpdateRole enforce
// freeze §6.2 rule #2 — "owner terakhir tidak bisa menghapus atau
// menurunkan dirinya sendiri" — without a race between reading the count
// and acting on it: both are called from inside the same Store.InTx as
// the write that depends on the answer.
func (r *postgresRepository) CountActiveOwners(ctx context.Context, t tenant.Context) (int, error) {
	const q = `SELECT count(*) FROM memberships WHERE organization_id = $1 AND role = 'owner' AND deleted_at IS NULL`
	var n int
	if err := r.q.QueryRow(ctx, q, t.OrganizationID).Scan(&n); err != nil {
		return 0, fmt.Errorf("membership: count active owners: %w", err)
	}
	return n, nil
}

// CountActive counts every active membership in t's organization —
// half of the seat meter (Phase 8.5). The other half is
// invitation.CountPendingSeats: an invitation nobody has accepted yet
// still holds a seat, or a 2-seat organization could send five
// invitations and end up with five members without a single check
// failing. Both halves are summed by the caller (TD 8.5 §6).
func (r *postgresRepository) CountActive(ctx context.Context, t tenant.Context) (int, error) {
	const q = `SELECT count(*) FROM memberships WHERE organization_id = $1 AND deleted_at IS NULL`
	var n int
	if err := r.q.QueryRow(ctx, q, t.OrganizationID).Scan(&n); err != nil {
		return 0, fmt.Errorf("membership: count active: %w", err)
	}
	return n, nil
}

// FindActiveOwnerIDs is the other consumer of the seat meter's
// neighbourhood: the recipients for Phase 8.5's quota-exceeded
// notification. See the interface doc comment for why it returns every
// active Owner rather than a single one.
func (r *postgresRepository) FindActiveOwnerIDs(ctx context.Context, t tenant.Context) ([]uuid.UUID, error) {
	const q = `SELECT id FROM memberships WHERE organization_id = $1 AND role = 'owner' AND deleted_at IS NULL`
	rows, err := r.q.Query(ctx, q, t.OrganizationID)
	if err != nil {
		return nil, fmt.Errorf("membership: find active owner ids: %w", err)
	}
	defer rows.Close()

	var ids []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("membership: scan owner id: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("membership: iterate owner ids: %w", err)
	}
	return ids, nil
}

// rowScanner is satisfied by both pgx.Row (QueryRow) and pgx.Rows
// (Query), letting scanOne and the row-scanning body share one Scan call
// shape.
type rowScanner interface {
	Scan(dest ...any) error
}

func scanOne(row rowScanner) (*Membership, error) {
	return scanRow(row)
}

func scanRow(row rowScanner) (*Membership, error) {
	var m Membership
	err := row.Scan(&m.ID, &m.OrganizationID, &m.UserID, &m.Role, &m.CreatedAt, &m.UpdatedAt, &m.DeletedAt)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
