package membership

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/Pravasta/jualin-crm/crm_be/internal/shared/db"
	"github.com/Pravasta/jualin-crm/crm_be/internal/shared/httpx"
	"github.com/Pravasta/jualin-crm/crm_be/internal/shared/tenant"
)

// Repository is the reference implementation every later tenant-scoped
// repository in this codebase copies. Every method takes tenant.Context
// as its first parameter and injects organization_id inside the query —
// it is never accepted as a separate argument a caller could get wrong,
// and there is no method here that omits it (docs/architecture/multi-tenancy.md
// lapis 1).
type Repository struct {
	q db.Querier
}

// New builds a Repository bound to q. Pass a *pgxpool.Pool for read-only
// use, or a pgx.Tx (inside db.InTx) when the write must be atomic with
// other tables — e.g. creating a membership alongside its organization
// during registration.
func New(q db.Querier) *Repository {
	return &Repository{q: q}
}

// FindByID returns the membership with id within t's organization.
// A membership belonging to another organization is indistinguishable
// from one that doesn't exist — it maps to httpx.ErrNotFound (404), never
// a 403 (Rule #6): a 403 would confirm the id exists, which is itself an
// information leak.
func (r *Repository) FindByID(ctx context.Context, t tenant.Context, id uuid.UUID) (*Membership, error) {
	const q = `
		SELECT id, organization_id, user_id, role, created_at, updated_at, deleted_at
		FROM memberships
		WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL`

	m, err := scanOne(r.q.QueryRow(ctx, q, id, t.OrganizationID))
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, httpx.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("membership: find by id: %w", err)
	}
	return m, nil
}

// FindActiveByUserID returns every non-deleted membership a user holds,
// across every organization they belong to — this is the query
// ADR-007's multi-membership model exists to support, used at login to
// decide whether organization selection is required.
//
// This is the one method on this repository that is NOT organization-
// scoped by design: a user resolving "which of my organizations can I
// log into" must see across all of them. It still takes tenant.Context
// so the signature matches every other repository method, but
// t.OrganizationID is intentionally unused here.
func (r *Repository) FindActiveByUserID(ctx context.Context, userID uuid.UUID) ([]*Membership, error) {
	const q = `
		SELECT id, organization_id, user_id, role, created_at, updated_at, deleted_at
		FROM memberships
		WHERE user_id = $1 AND deleted_at IS NULL
		ORDER BY created_at`

	rows, err := r.q.Query(ctx, q, userID)
	if err != nil {
		return nil, fmt.Errorf("membership: find active by user id: %w", err)
	}
	defer rows.Close()

	var out []*Membership
	for rows.Next() {
		m, err := scanRow(rows)
		if err != nil {
			return nil, fmt.Errorf("membership: scan: %w", err)
		}
		out = append(out, m)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("membership: find active by user id: %w", err)
	}
	return out, nil
}

// Create inserts a new membership. The caller supplies id (UUIDv7,
// generated by the application per Rule #12 — never a database DEFAULT).
func (r *Repository) Create(ctx context.Context, t tenant.Context, id, userID uuid.UUID, role tenant.Role) (*Membership, error) {
	const q = `
		INSERT INTO memberships (id, organization_id, user_id, role)
		VALUES ($1, $2, $3, $4)
		RETURNING id, organization_id, user_id, role, created_at, updated_at, deleted_at`

	m, err := scanOne(r.q.QueryRow(ctx, q, id, t.OrganizationID, userID, role))
	if err != nil {
		return nil, fmt.Errorf("membership: create: %w", err)
	}
	return m, nil
}

// rowScanner is satisfied by both pgx.Row (QueryRow) and pgx.Rows
// (Query), letting scanOne and the row-scanning body share one Scan call
// shape.
type rowScanner interface {
	Scan(dest ...any) error
}

func scanOne(row rowScanner) (*Membership, error) {
	return scanRow(row)
}

func scanRow(row rowScanner) (*Membership, error) {
	var m Membership
	err := row.Scan(&m.ID, &m.OrganizationID, &m.UserID, &m.Role, &m.CreatedAt, &m.UpdatedAt, &m.DeletedAt)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
